// <auto-generated />
namespace CashReceipts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class adding_Payment_Methods_Enum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_Payment_Methods_Enum));
        
        string IMigrationMetadata.Id
        {
            get { return "201606022253285_adding_Payment_Methods_Enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
