// <auto-generated />
namespace CashReceipts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tenders_DescriptionIsNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tenders_DescriptionIsNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201608030114105_Tenders_DescriptionIsNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
