// <auto-generated />
namespace CashReceipts
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Templates_Departments_DeleteAction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Templates_Departments_DeleteAction));
        
        string IMigrationMetadata.Id
        {
            get { return "201612150022541_Templates_Departments_DeleteAction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
