// <auto-generated />
namespace CashReceipts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ScreensFeatures_Lookup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScreensFeatures_Lookup));
        
        string IMigrationMetadata.Id
        {
            get { return "201703141808301_ScreensFeatures_Lookup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
