// <auto-generated />
namespace CashReceipts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ScreenFeatures_Add_Missing : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ScreenFeatures_Add_Missing));
        
        string IMigrationMetadata.Id
        {
            get { return "201703192239315_ScreenFeatures_Add_Missing"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
