// <auto-generated />
namespace CashReceipts.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddNew_TendersSearch_Screen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNew_TendersSearch_Screen));
        
        string IMigrationMetadata.Id
        {
            get { return "201805020107486_AddNew_TendersSearch_Screen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
