namespace CashReceipts.ViewModels
{
    public enum FeaturePermissions
    {
        UsersIndex = 1,
        EditUserRole = 2,
        ClerksIndex = 3,
        CreateClerks = 4,
        EditClerks = 5,
        ViewClerks = 6,
        DeleteClerks = 7,
        EntitiesIndex = 8,
        CreateEntity = 9,
        EditEntity = 10,
        ViewEntity = 11,
        DeleteEntity = 12,
        DepartmentIndex = 13,
        CreateDepartment = 14,
        EditDepartment = 15,
        ViewDepartment = 16,
        DeleteDepartment = 17,
        SystemAccountIndex = 18,
        EditSystemAccount = 19,
        ViewSystemAccount = 20,
        DeleteSystemAccount = 21,
        ManageReceiptsIndex = 22,
        AddNewReceipt = 23,
        DownloadReceipt = 24,
        PostReceipt = 25,
        AddReceiptItem = 26,
        EditReceiptItem = 27,
        DeleteReceiptItem = 28,
        AddTenderItem = 44,
        EditTenderItem = 45,
        DeleteTenderItem = 46,
        AddReceiptBody = 48,
        EditReceiptBody = 49,
        DeleteReceiptBody = 50,
        SearchLineItemIndex = 29,
        ExportLineItem = 30,
        ShowReceipt = 31,
        ReceiptsExportIndex = 32,
        ReceiptsExport = 33,
        LineItemsExport = 34,
        TendersExport = 35,
        ReceiptsDetailsExport = 36,
        DaySummaryReportIndex = 37,
        ExportAndPrintSummary = 38,
        AuditsIndex = 39,
        GrantCountyAccountIndex = 40,
        DistrictsAccountIndex = 41,
        PrintReceipt = 42,
        LockReceipt = 51,
        LockReceipts = 52,
        SearchTenders = 53,
        ExportTenders = 54,
    }
}